# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Prototype.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(461, 458)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("mslogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.InputsGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.InputsGroup.setObjectName("InputsGroup")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.InputsGroup)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.inputLabel = QtWidgets.QLabel(self.InputsGroup)
        self.inputLabel.setObjectName("inputLabel")
        self.gridLayout_4.addWidget(self.inputLabel, 0, 0, 1, 1)
        self.inputText = QtWidgets.QLineEdit(self.InputsGroup)
        self.inputText.setObjectName("inputText")
        self.gridLayout_4.addWidget(self.inputText, 0, 1, 1, 1)
        self.outputLabel = QtWidgets.QLabel(self.InputsGroup)
        self.outputLabel.setObjectName("outputLabel")
        self.gridLayout_4.addWidget(self.outputLabel, 1, 0, 1, 1)
        self.outputText = QtWidgets.QLineEdit(self.InputsGroup)
        self.outputText.setStatusTip("")
        self.outputText.setWhatsThis("")
        self.outputText.setAccessibleName("")
        self.outputText.setAutoFillBackground(False)
        self.outputText.setInputMask("")
        self.outputText.setText("")
        self.outputText.setObjectName("outputText")
        self.gridLayout_4.addWidget(self.outputText, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.InputsGroup, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 1, 0, 1, 1)
        self.DistributionGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.DistributionGroup.setObjectName("DistributionGroup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.DistributionGroup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ForceLabel = QtWidgets.QLabel(self.DistributionGroup)
        self.ForceLabel.setObjectName("ForceLabel")
        self.gridLayout_3.addWidget(self.ForceLabel, 0, 0, 1, 1)
        self.ForceYes = QtWidgets.QRadioButton(self.DistributionGroup)
        self.ForceYes.setChecked(True)
        self.ForceYes.setObjectName("ForceYes")
        self.gridLayout_3.addWidget(self.ForceYes, 0, 1, 1, 1)
        self.ForceNo = QtWidgets.QRadioButton(self.DistributionGroup)
        self.ForceNo.setChecked(False)
        self.ForceNo.setObjectName("ForceNo")
        self.gridLayout_3.addWidget(self.ForceNo, 0, 2, 1, 1)
        self.NumbeOfCasesLabel = QtWidgets.QLabel(self.DistributionGroup)
        self.NumbeOfCasesLabel.setObjectName("NumbeOfCasesLabel")
        self.gridLayout_3.addWidget(self.NumbeOfCasesLabel, 1, 0, 1, 3)
        self.NumberOfCasesText = QtWidgets.QLineEdit(self.DistributionGroup)
        self.NumberOfCasesText.setReadOnly(False)
        self.NumberOfCasesText.setClearButtonEnabled(False)
        self.NumberOfCasesText.setObjectName("NumberOfCasesText")
        self.gridLayout_3.addWidget(self.NumberOfCasesText, 1, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 4, 1, 1)
        self.gridLayout_2.addWidget(self.DistributionGroup, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 3, 0, 1, 1)
        self.VariationCategoriesGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.VariationCategoriesGroup.setObjectName("VariationCategoriesGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.VariationCategoriesGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.Initials = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.Initials.setChecked(True)
        self.Initials.setObjectName("Initials")
        self.gridLayout.addWidget(self.Initials, 0, 0, 1, 1)
        self.InitialsPerc = QtWidgets.QComboBox(self.VariationCategoriesGroup)
        self.InitialsPerc.setAcceptDrops(False)
        self.InitialsPerc.setObjectName("InitialsPerc")
        self.InitialsPerc.addItem("")
        self.InitialsPerc.addItem("")
        self.InitialsPerc.addItem("")
        self.InitialsPerc.addItem("")
        self.InitialsPerc.addItem("")
        self.InitialsPerc.addItem("")
        self.InitialsPerc.addItem("")
        self.InitialsPerc.addItem("")
        self.InitialsPerc.addItem("")
        self.InitialsPerc.addItem("")
        self.InitialsPerc.addItem("")
        self.InitialsPerc.addItem("")
        self.InitialsPerc.addItem("")
        self.InitialsPerc.addItem("")
        self.InitialsPerc.addItem("")
        self.InitialsPerc.addItem("")
        self.InitialsPerc.addItem("")
        self.InitialsPerc.addItem("")
        self.InitialsPerc.addItem("")
        self.InitialsPerc.addItem("")
        self.InitialsPerc.addItem("")
        self.gridLayout.addWidget(self.InitialsPerc, 0, 1, 1, 1)
        self.DoubleCharacters = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.DoubleCharacters.setChecked(True)
        self.DoubleCharacters.setObjectName("DoubleCharacters")
        self.gridLayout.addWidget(self.DoubleCharacters, 0, 2, 1, 1)
        self.DoubleCharPerc = QtWidgets.QComboBox(self.VariationCategoriesGroup)
        self.DoubleCharPerc.setObjectName("DoubleCharPerc")
        self.DoubleCharPerc.addItem("")
        self.DoubleCharPerc.addItem("")
        self.DoubleCharPerc.addItem("")
        self.DoubleCharPerc.addItem("")
        self.DoubleCharPerc.addItem("")
        self.DoubleCharPerc.addItem("")
        self.DoubleCharPerc.addItem("")
        self.DoubleCharPerc.addItem("")
        self.DoubleCharPerc.addItem("")
        self.DoubleCharPerc.addItem("")
        self.DoubleCharPerc.addItem("")
        self.DoubleCharPerc.addItem("")
        self.DoubleCharPerc.addItem("")
        self.DoubleCharPerc.addItem("")
        self.DoubleCharPerc.addItem("")
        self.DoubleCharPerc.addItem("")
        self.DoubleCharPerc.addItem("")
        self.DoubleCharPerc.addItem("")
        self.DoubleCharPerc.addItem("")
        self.DoubleCharPerc.addItem("")
        self.DoubleCharPerc.addItem("")
        self.gridLayout.addWidget(self.DoubleCharPerc, 0, 3, 1, 1)
        self.CharacterExtension = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.CharacterExtension.setChecked(True)
        self.CharacterExtension.setObjectName("CharacterExtension")
        self.gridLayout.addWidget(self.CharacterExtension, 1, 0, 1, 1)
        self.CharExtPerc = QtWidgets.QComboBox(self.VariationCategoriesGroup)
        self.CharExtPerc.setObjectName("CharExtPerc")
        self.CharExtPerc.addItem("")
        self.CharExtPerc.addItem("")
        self.CharExtPerc.addItem("")
        self.CharExtPerc.addItem("")
        self.CharExtPerc.addItem("")
        self.CharExtPerc.addItem("")
        self.CharExtPerc.addItem("")
        self.CharExtPerc.addItem("")
        self.CharExtPerc.addItem("")
        self.CharExtPerc.addItem("")
        self.CharExtPerc.addItem("")
        self.CharExtPerc.addItem("")
        self.CharExtPerc.addItem("")
        self.CharExtPerc.addItem("")
        self.CharExtPerc.addItem("")
        self.CharExtPerc.addItem("")
        self.CharExtPerc.addItem("")
        self.CharExtPerc.addItem("")
        self.CharExtPerc.addItem("")
        self.CharExtPerc.addItem("")
        self.CharExtPerc.addItem("")
        self.gridLayout.addWidget(self.CharExtPerc, 1, 1, 1, 1)
        self.Spaces = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.Spaces.setChecked(True)
        self.Spaces.setObjectName("Spaces")
        self.gridLayout.addWidget(self.Spaces, 1, 2, 1, 1)
        self.SpacesPerc = QtWidgets.QComboBox(self.VariationCategoriesGroup)
        self.SpacesPerc.setObjectName("SpacesPerc")
        self.SpacesPerc.addItem("")
        self.SpacesPerc.addItem("")
        self.SpacesPerc.addItem("")
        self.SpacesPerc.addItem("")
        self.SpacesPerc.addItem("")
        self.SpacesPerc.addItem("")
        self.SpacesPerc.addItem("")
        self.SpacesPerc.addItem("")
        self.SpacesPerc.addItem("")
        self.SpacesPerc.addItem("")
        self.SpacesPerc.addItem("")
        self.SpacesPerc.addItem("")
        self.SpacesPerc.addItem("")
        self.SpacesPerc.addItem("")
        self.SpacesPerc.addItem("")
        self.SpacesPerc.addItem("")
        self.SpacesPerc.addItem("")
        self.SpacesPerc.addItem("")
        self.SpacesPerc.addItem("")
        self.SpacesPerc.addItem("")
        self.SpacesPerc.addItem("")
        self.gridLayout.addWidget(self.SpacesPerc, 1, 3, 1, 1)
        self.CharacterReplacement = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.CharacterReplacement.setChecked(True)
        self.CharacterReplacement.setObjectName("CharacterReplacement")
        self.gridLayout.addWidget(self.CharacterReplacement, 2, 0, 1, 1)
        self.CharRepPerc = QtWidgets.QComboBox(self.VariationCategoriesGroup)
        self.CharRepPerc.setObjectName("CharRepPerc")
        self.CharRepPerc.addItem("")
        self.CharRepPerc.addItem("")
        self.CharRepPerc.addItem("")
        self.CharRepPerc.addItem("")
        self.CharRepPerc.addItem("")
        self.CharRepPerc.addItem("")
        self.CharRepPerc.addItem("")
        self.CharRepPerc.addItem("")
        self.CharRepPerc.addItem("")
        self.CharRepPerc.addItem("")
        self.CharRepPerc.addItem("")
        self.CharRepPerc.addItem("")
        self.CharRepPerc.addItem("")
        self.CharRepPerc.addItem("")
        self.CharRepPerc.addItem("")
        self.CharRepPerc.addItem("")
        self.CharRepPerc.addItem("")
        self.CharRepPerc.addItem("")
        self.CharRepPerc.addItem("")
        self.CharRepPerc.addItem("")
        self.CharRepPerc.addItem("")
        self.gridLayout.addWidget(self.CharRepPerc, 2, 1, 1, 1)
        self.NameOrder = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.NameOrder.setChecked(True)
        self.NameOrder.setObjectName("NameOrder")
        self.gridLayout.addWidget(self.NameOrder, 2, 2, 1, 1)
        self.NameOrderPerc = QtWidgets.QComboBox(self.VariationCategoriesGroup)
        self.NameOrderPerc.setObjectName("NameOrderPerc")
        self.NameOrderPerc.addItem("")
        self.NameOrderPerc.addItem("")
        self.NameOrderPerc.addItem("")
        self.NameOrderPerc.addItem("")
        self.NameOrderPerc.addItem("")
        self.NameOrderPerc.addItem("")
        self.NameOrderPerc.addItem("")
        self.NameOrderPerc.addItem("")
        self.NameOrderPerc.addItem("")
        self.NameOrderPerc.addItem("")
        self.NameOrderPerc.addItem("")
        self.NameOrderPerc.addItem("")
        self.NameOrderPerc.addItem("")
        self.NameOrderPerc.addItem("")
        self.NameOrderPerc.addItem("")
        self.NameOrderPerc.addItem("")
        self.NameOrderPerc.addItem("")
        self.NameOrderPerc.addItem("")
        self.NameOrderPerc.addItem("")
        self.NameOrderPerc.addItem("")
        self.NameOrderPerc.addItem("")
        self.gridLayout.addWidget(self.NameOrderPerc, 2, 3, 1, 1)
        self.CharacterReduction = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.CharacterReduction.setChecked(True)
        self.CharacterReduction.setObjectName("CharacterReduction")
        self.gridLayout.addWidget(self.CharacterReduction, 3, 0, 1, 1)
        self.CharRedPerc = QtWidgets.QComboBox(self.VariationCategoriesGroup)
        self.CharRedPerc.setObjectName("CharRedPerc")
        self.CharRedPerc.addItem("")
        self.CharRedPerc.addItem("")
        self.CharRedPerc.addItem("")
        self.CharRedPerc.addItem("")
        self.CharRedPerc.addItem("")
        self.CharRedPerc.addItem("")
        self.CharRedPerc.addItem("")
        self.CharRedPerc.addItem("")
        self.CharRedPerc.addItem("")
        self.CharRedPerc.addItem("")
        self.CharRedPerc.addItem("")
        self.CharRedPerc.addItem("")
        self.CharRedPerc.addItem("")
        self.CharRedPerc.addItem("")
        self.CharRedPerc.addItem("")
        self.CharRedPerc.addItem("")
        self.CharRedPerc.addItem("")
        self.CharRedPerc.addItem("")
        self.CharRedPerc.addItem("")
        self.CharRedPerc.addItem("")
        self.CharRedPerc.addItem("")
        self.gridLayout.addWidget(self.CharRedPerc, 3, 1, 1, 1)
        self.Titles = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.Titles.setChecked(True)
        self.Titles.setObjectName("Titles")
        self.gridLayout.addWidget(self.Titles, 3, 2, 1, 1)
        self.TitlesPerc = QtWidgets.QComboBox(self.VariationCategoriesGroup)
        self.TitlesPerc.setObjectName("TitlesPerc")
        self.TitlesPerc.addItem("")
        self.TitlesPerc.addItem("")
        self.TitlesPerc.addItem("")
        self.TitlesPerc.addItem("")
        self.TitlesPerc.addItem("")
        self.TitlesPerc.addItem("")
        self.TitlesPerc.addItem("")
        self.TitlesPerc.addItem("")
        self.TitlesPerc.addItem("")
        self.TitlesPerc.addItem("")
        self.TitlesPerc.addItem("")
        self.TitlesPerc.addItem("")
        self.TitlesPerc.addItem("")
        self.TitlesPerc.addItem("")
        self.TitlesPerc.addItem("")
        self.TitlesPerc.addItem("")
        self.TitlesPerc.addItem("")
        self.TitlesPerc.addItem("")
        self.TitlesPerc.addItem("")
        self.TitlesPerc.addItem("")
        self.TitlesPerc.addItem("")
        self.gridLayout.addWidget(self.TitlesPerc, 3, 3, 1, 1)
        self.Transposition = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.Transposition.setChecked(True)
        self.Transposition.setObjectName("Transposition")
        self.gridLayout.addWidget(self.Transposition, 4, 0, 1, 1)
        self.TranspositionPerc = QtWidgets.QComboBox(self.VariationCategoriesGroup)
        self.TranspositionPerc.setObjectName("TranspositionPerc")
        self.TranspositionPerc.addItem("")
        self.TranspositionPerc.addItem("")
        self.TranspositionPerc.addItem("")
        self.TranspositionPerc.addItem("")
        self.TranspositionPerc.addItem("")
        self.TranspositionPerc.addItem("")
        self.TranspositionPerc.addItem("")
        self.TranspositionPerc.addItem("")
        self.TranspositionPerc.addItem("")
        self.TranspositionPerc.addItem("")
        self.TranspositionPerc.addItem("")
        self.TranspositionPerc.addItem("")
        self.TranspositionPerc.addItem("")
        self.TranspositionPerc.addItem("")
        self.TranspositionPerc.addItem("")
        self.TranspositionPerc.addItem("")
        self.TranspositionPerc.addItem("")
        self.TranspositionPerc.addItem("")
        self.TranspositionPerc.addItem("")
        self.TranspositionPerc.addItem("")
        self.TranspositionPerc.addItem("")
        self.gridLayout.addWidget(self.TranspositionPerc, 4, 1, 1, 1)
        self.MissingNameComp = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.MissingNameComp.setChecked(True)
        self.MissingNameComp.setObjectName("MissingNameComp")
        self.gridLayout.addWidget(self.MissingNameComp, 4, 2, 1, 1)
        self.MissNameCompPerc = QtWidgets.QComboBox(self.VariationCategoriesGroup)
        self.MissNameCompPerc.setObjectName("MissNameCompPerc")
        self.MissNameCompPerc.addItem("")
        self.MissNameCompPerc.addItem("")
        self.MissNameCompPerc.addItem("")
        self.MissNameCompPerc.addItem("")
        self.MissNameCompPerc.addItem("")
        self.MissNameCompPerc.addItem("")
        self.MissNameCompPerc.addItem("")
        self.MissNameCompPerc.addItem("")
        self.MissNameCompPerc.addItem("")
        self.MissNameCompPerc.addItem("")
        self.MissNameCompPerc.addItem("")
        self.MissNameCompPerc.addItem("")
        self.MissNameCompPerc.addItem("")
        self.MissNameCompPerc.addItem("")
        self.MissNameCompPerc.addItem("")
        self.MissNameCompPerc.addItem("")
        self.MissNameCompPerc.addItem("")
        self.MissNameCompPerc.addItem("")
        self.MissNameCompPerc.addItem("")
        self.MissNameCompPerc.addItem("")
        self.MissNameCompPerc.addItem("")
        self.gridLayout.addWidget(self.MissNameCompPerc, 4, 3, 1, 1)
        self.AlsoKnownAs = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.AlsoKnownAs.setEnabled(True)
        self.AlsoKnownAs.setChecked(True)
        self.AlsoKnownAs.setObjectName("AlsoKnownAs")
        self.gridLayout.addWidget(self.AlsoKnownAs, 5, 2, 1, 1)
        self.AlsoKnownAsPerc = QtWidgets.QComboBox(self.VariationCategoriesGroup)
        self.AlsoKnownAsPerc.setObjectName("AlsoKnownAsPerc")
        self.AlsoKnownAsPerc.addItem("")
        self.AlsoKnownAsPerc.addItem("")
        self.AlsoKnownAsPerc.addItem("")
        self.AlsoKnownAsPerc.addItem("")
        self.AlsoKnownAsPerc.addItem("")
        self.AlsoKnownAsPerc.addItem("")
        self.AlsoKnownAsPerc.addItem("")
        self.AlsoKnownAsPerc.addItem("")
        self.AlsoKnownAsPerc.addItem("")
        self.AlsoKnownAsPerc.addItem("")
        self.AlsoKnownAsPerc.addItem("")
        self.AlsoKnownAsPerc.addItem("")
        self.AlsoKnownAsPerc.addItem("")
        self.AlsoKnownAsPerc.addItem("")
        self.AlsoKnownAsPerc.addItem("")
        self.AlsoKnownAsPerc.addItem("")
        self.AlsoKnownAsPerc.addItem("")
        self.AlsoKnownAsPerc.addItem("")
        self.AlsoKnownAsPerc.addItem("")
        self.AlsoKnownAsPerc.addItem("")
        self.AlsoKnownAsPerc.addItem("")
        self.gridLayout.addWidget(self.AlsoKnownAsPerc, 5, 3, 1, 1)
        self.gridLayout_2.addWidget(self.VariationCategoriesGroup, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setObjectName("submitButton")
        self.horizontalLayout_2.addWidget(self.submitButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 461, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.ForceNo.toggled['bool'].connect(self.NumberOfCasesText.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.InitialsPerc.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.CharExtPerc.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.CharRepPerc.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.CharRedPerc.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.TranspositionPerc.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.DoubleCharPerc.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.SpacesPerc.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.NameOrderPerc.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.TitlesPerc.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.MissNameCompPerc.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.AlsoKnownAsPerc.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Prototype"))
        self.InputsGroup.setTitle(_translate("MainWindow", "Inputs"))
        self.inputLabel.setText(_translate("MainWindow", "Input path:"))
        self.inputText.setPlaceholderText(_translate("MainWindow", "C:\\Program Files\\Your Folder\\Your Subfolder\\Your_csv.csv"))
        self.outputLabel.setText(_translate("MainWindow", "Output path:"))
        self.outputText.setPlaceholderText(_translate("MainWindow", "C:\\Program Files\\Your Folder\\Your Subfolder\\Your_csv.csv"))
        self.DistributionGroup.setTitle(_translate("MainWindow", "Distribution"))
        self.ForceLabel.setText(_translate("MainWindow", "Force Distribution:"))
        self.ForceYes.setText(_translate("MainWindow", "Yes"))
        self.ForceNo.setText(_translate("MainWindow", "No"))
        self.NumbeOfCasesLabel.setText(_translate("MainWindow", "Number of test cases to be generated:"))
        self.NumberOfCasesText.setPlaceholderText(_translate("MainWindow", "e.g. 100"))
        self.VariationCategoriesGroup.setTitle(_translate("MainWindow", "Variation Categories"))
        self.Initials.setText(_translate("MainWindow", "Initials"))
        self.InitialsPerc.setItemText(0, _translate("MainWindow", "0%"))
        self.InitialsPerc.setItemText(1, _translate("MainWindow", "5%"))
        self.InitialsPerc.setItemText(2, _translate("MainWindow", "10%"))
        self.InitialsPerc.setItemText(3, _translate("MainWindow", "15%"))
        self.InitialsPerc.setItemText(4, _translate("MainWindow", "20%"))
        self.InitialsPerc.setItemText(5, _translate("MainWindow", "25%"))
        self.InitialsPerc.setItemText(6, _translate("MainWindow", "30%"))
        self.InitialsPerc.setItemText(7, _translate("MainWindow", "35%"))
        self.InitialsPerc.setItemText(8, _translate("MainWindow", "40%"))
        self.InitialsPerc.setItemText(9, _translate("MainWindow", "45%"))
        self.InitialsPerc.setItemText(10, _translate("MainWindow", "50%"))
        self.InitialsPerc.setItemText(11, _translate("MainWindow", "55%"))
        self.InitialsPerc.setItemText(12, _translate("MainWindow", "60%"))
        self.InitialsPerc.setItemText(13, _translate("MainWindow", "65%"))
        self.InitialsPerc.setItemText(14, _translate("MainWindow", "70%"))
        self.InitialsPerc.setItemText(15, _translate("MainWindow", "75%"))
        self.InitialsPerc.setItemText(16, _translate("MainWindow", "80%"))
        self.InitialsPerc.setItemText(17, _translate("MainWindow", "85%"))
        self.InitialsPerc.setItemText(18, _translate("MainWindow", "90%"))
        self.InitialsPerc.setItemText(19, _translate("MainWindow", "95%"))
        self.InitialsPerc.setItemText(20, _translate("MainWindow", "100%"))
        self.DoubleCharacters.setText(_translate("MainWindow", "Double Characters"))
        self.DoubleCharPerc.setItemText(0, _translate("MainWindow", "0%"))
        self.DoubleCharPerc.setItemText(1, _translate("MainWindow", "5%"))
        self.DoubleCharPerc.setItemText(2, _translate("MainWindow", "10%"))
        self.DoubleCharPerc.setItemText(3, _translate("MainWindow", "15%"))
        self.DoubleCharPerc.setItemText(4, _translate("MainWindow", "20%"))
        self.DoubleCharPerc.setItemText(5, _translate("MainWindow", "25%"))
        self.DoubleCharPerc.setItemText(6, _translate("MainWindow", "30%"))
        self.DoubleCharPerc.setItemText(7, _translate("MainWindow", "35%"))
        self.DoubleCharPerc.setItemText(8, _translate("MainWindow", "40%"))
        self.DoubleCharPerc.setItemText(9, _translate("MainWindow", "45%"))
        self.DoubleCharPerc.setItemText(10, _translate("MainWindow", "50%"))
        self.DoubleCharPerc.setItemText(11, _translate("MainWindow", "55%"))
        self.DoubleCharPerc.setItemText(12, _translate("MainWindow", "60%"))
        self.DoubleCharPerc.setItemText(13, _translate("MainWindow", "65%"))
        self.DoubleCharPerc.setItemText(14, _translate("MainWindow", "70%"))
        self.DoubleCharPerc.setItemText(15, _translate("MainWindow", "75%"))
        self.DoubleCharPerc.setItemText(16, _translate("MainWindow", "80%"))
        self.DoubleCharPerc.setItemText(17, _translate("MainWindow", "85%"))
        self.DoubleCharPerc.setItemText(18, _translate("MainWindow", "90%"))
        self.DoubleCharPerc.setItemText(19, _translate("MainWindow", "95%"))
        self.DoubleCharPerc.setItemText(20, _translate("MainWindow", "100%"))
        self.CharacterExtension.setText(_translate("MainWindow", "Character Extension"))
        self.CharExtPerc.setItemText(0, _translate("MainWindow", "0%"))
        self.CharExtPerc.setItemText(1, _translate("MainWindow", "5%"))
        self.CharExtPerc.setItemText(2, _translate("MainWindow", "10%"))
        self.CharExtPerc.setItemText(3, _translate("MainWindow", "15%"))
        self.CharExtPerc.setItemText(4, _translate("MainWindow", "20%"))
        self.CharExtPerc.setItemText(5, _translate("MainWindow", "25%"))
        self.CharExtPerc.setItemText(6, _translate("MainWindow", "30%"))
        self.CharExtPerc.setItemText(7, _translate("MainWindow", "35%"))
        self.CharExtPerc.setItemText(8, _translate("MainWindow", "40%"))
        self.CharExtPerc.setItemText(9, _translate("MainWindow", "45%"))
        self.CharExtPerc.setItemText(10, _translate("MainWindow", "50%"))
        self.CharExtPerc.setItemText(11, _translate("MainWindow", "55%"))
        self.CharExtPerc.setItemText(12, _translate("MainWindow", "60%"))
        self.CharExtPerc.setItemText(13, _translate("MainWindow", "65%"))
        self.CharExtPerc.setItemText(14, _translate("MainWindow", "70%"))
        self.CharExtPerc.setItemText(15, _translate("MainWindow", "75%"))
        self.CharExtPerc.setItemText(16, _translate("MainWindow", "80%"))
        self.CharExtPerc.setItemText(17, _translate("MainWindow", "85%"))
        self.CharExtPerc.setItemText(18, _translate("MainWindow", "90%"))
        self.CharExtPerc.setItemText(19, _translate("MainWindow", "95%"))
        self.CharExtPerc.setItemText(20, _translate("MainWindow", "100%"))
        self.Spaces.setText(_translate("MainWindow", "Spaces"))
        self.SpacesPerc.setItemText(0, _translate("MainWindow", "0%"))
        self.SpacesPerc.setItemText(1, _translate("MainWindow", "5%"))
        self.SpacesPerc.setItemText(2, _translate("MainWindow", "10%"))
        self.SpacesPerc.setItemText(3, _translate("MainWindow", "15%"))
        self.SpacesPerc.setItemText(4, _translate("MainWindow", "20%"))
        self.SpacesPerc.setItemText(5, _translate("MainWindow", "25%"))
        self.SpacesPerc.setItemText(6, _translate("MainWindow", "30%"))
        self.SpacesPerc.setItemText(7, _translate("MainWindow", "35%"))
        self.SpacesPerc.setItemText(8, _translate("MainWindow", "40%"))
        self.SpacesPerc.setItemText(9, _translate("MainWindow", "45%"))
        self.SpacesPerc.setItemText(10, _translate("MainWindow", "50%"))
        self.SpacesPerc.setItemText(11, _translate("MainWindow", "55%"))
        self.SpacesPerc.setItemText(12, _translate("MainWindow", "60%"))
        self.SpacesPerc.setItemText(13, _translate("MainWindow", "65%"))
        self.SpacesPerc.setItemText(14, _translate("MainWindow", "70%"))
        self.SpacesPerc.setItemText(15, _translate("MainWindow", "75%"))
        self.SpacesPerc.setItemText(16, _translate("MainWindow", "80%"))
        self.SpacesPerc.setItemText(17, _translate("MainWindow", "85%"))
        self.SpacesPerc.setItemText(18, _translate("MainWindow", "90%"))
        self.SpacesPerc.setItemText(19, _translate("MainWindow", "95%"))
        self.SpacesPerc.setItemText(20, _translate("MainWindow", "100%"))
        self.CharacterReplacement.setText(_translate("MainWindow", "Character Replacement"))
        self.CharRepPerc.setItemText(0, _translate("MainWindow", "0%"))
        self.CharRepPerc.setItemText(1, _translate("MainWindow", "5%"))
        self.CharRepPerc.setItemText(2, _translate("MainWindow", "10%"))
        self.CharRepPerc.setItemText(3, _translate("MainWindow", "15%"))
        self.CharRepPerc.setItemText(4, _translate("MainWindow", "20%"))
        self.CharRepPerc.setItemText(5, _translate("MainWindow", "25%"))
        self.CharRepPerc.setItemText(6, _translate("MainWindow", "30%"))
        self.CharRepPerc.setItemText(7, _translate("MainWindow", "35%"))
        self.CharRepPerc.setItemText(8, _translate("MainWindow", "40%"))
        self.CharRepPerc.setItemText(9, _translate("MainWindow", "45%"))
        self.CharRepPerc.setItemText(10, _translate("MainWindow", "50%"))
        self.CharRepPerc.setItemText(11, _translate("MainWindow", "55%"))
        self.CharRepPerc.setItemText(12, _translate("MainWindow", "60%"))
        self.CharRepPerc.setItemText(13, _translate("MainWindow", "65%"))
        self.CharRepPerc.setItemText(14, _translate("MainWindow", "70%"))
        self.CharRepPerc.setItemText(15, _translate("MainWindow", "75%"))
        self.CharRepPerc.setItemText(16, _translate("MainWindow", "80%"))
        self.CharRepPerc.setItemText(17, _translate("MainWindow", "85%"))
        self.CharRepPerc.setItemText(18, _translate("MainWindow", "90%"))
        self.CharRepPerc.setItemText(19, _translate("MainWindow", "95%"))
        self.CharRepPerc.setItemText(20, _translate("MainWindow", "100%"))
        self.NameOrder.setText(_translate("MainWindow", "Name Order"))
        self.NameOrderPerc.setItemText(0, _translate("MainWindow", "0%"))
        self.NameOrderPerc.setItemText(1, _translate("MainWindow", "5%"))
        self.NameOrderPerc.setItemText(2, _translate("MainWindow", "10%"))
        self.NameOrderPerc.setItemText(3, _translate("MainWindow", "15%"))
        self.NameOrderPerc.setItemText(4, _translate("MainWindow", "20%"))
        self.NameOrderPerc.setItemText(5, _translate("MainWindow", "25%"))
        self.NameOrderPerc.setItemText(6, _translate("MainWindow", "30%"))
        self.NameOrderPerc.setItemText(7, _translate("MainWindow", "35%"))
        self.NameOrderPerc.setItemText(8, _translate("MainWindow", "40%"))
        self.NameOrderPerc.setItemText(9, _translate("MainWindow", "45%"))
        self.NameOrderPerc.setItemText(10, _translate("MainWindow", "50%"))
        self.NameOrderPerc.setItemText(11, _translate("MainWindow", "55%"))
        self.NameOrderPerc.setItemText(12, _translate("MainWindow", "60%"))
        self.NameOrderPerc.setItemText(13, _translate("MainWindow", "65%"))
        self.NameOrderPerc.setItemText(14, _translate("MainWindow", "70%"))
        self.NameOrderPerc.setItemText(15, _translate("MainWindow", "75%"))
        self.NameOrderPerc.setItemText(16, _translate("MainWindow", "80%"))
        self.NameOrderPerc.setItemText(17, _translate("MainWindow", "85%"))
        self.NameOrderPerc.setItemText(18, _translate("MainWindow", "90%"))
        self.NameOrderPerc.setItemText(19, _translate("MainWindow", "95%"))
        self.NameOrderPerc.setItemText(20, _translate("MainWindow", "100%"))
        self.CharacterReduction.setText(_translate("MainWindow", "Character Reduction"))
        self.CharRedPerc.setItemText(0, _translate("MainWindow", "0%"))
        self.CharRedPerc.setItemText(1, _translate("MainWindow", "5%"))
        self.CharRedPerc.setItemText(2, _translate("MainWindow", "10%"))
        self.CharRedPerc.setItemText(3, _translate("MainWindow", "15%"))
        self.CharRedPerc.setItemText(4, _translate("MainWindow", "20%"))
        self.CharRedPerc.setItemText(5, _translate("MainWindow", "25%"))
        self.CharRedPerc.setItemText(6, _translate("MainWindow", "30%"))
        self.CharRedPerc.setItemText(7, _translate("MainWindow", "35%"))
        self.CharRedPerc.setItemText(8, _translate("MainWindow", "40%"))
        self.CharRedPerc.setItemText(9, _translate("MainWindow", "45%"))
        self.CharRedPerc.setItemText(10, _translate("MainWindow", "50%"))
        self.CharRedPerc.setItemText(11, _translate("MainWindow", "55%"))
        self.CharRedPerc.setItemText(12, _translate("MainWindow", "60%"))
        self.CharRedPerc.setItemText(13, _translate("MainWindow", "65%"))
        self.CharRedPerc.setItemText(14, _translate("MainWindow", "70%"))
        self.CharRedPerc.setItemText(15, _translate("MainWindow", "75%"))
        self.CharRedPerc.setItemText(16, _translate("MainWindow", "80%"))
        self.CharRedPerc.setItemText(17, _translate("MainWindow", "85%"))
        self.CharRedPerc.setItemText(18, _translate("MainWindow", "90%"))
        self.CharRedPerc.setItemText(19, _translate("MainWindow", "95%"))
        self.CharRedPerc.setItemText(20, _translate("MainWindow", "100%"))
        self.Titles.setText(_translate("MainWindow", "Titles"))
        self.TitlesPerc.setItemText(0, _translate("MainWindow", "0%"))
        self.TitlesPerc.setItemText(1, _translate("MainWindow", "5%"))
        self.TitlesPerc.setItemText(2, _translate("MainWindow", "10%"))
        self.TitlesPerc.setItemText(3, _translate("MainWindow", "15%"))
        self.TitlesPerc.setItemText(4, _translate("MainWindow", "20%"))
        self.TitlesPerc.setItemText(5, _translate("MainWindow", "25%"))
        self.TitlesPerc.setItemText(6, _translate("MainWindow", "30%"))
        self.TitlesPerc.setItemText(7, _translate("MainWindow", "35%"))
        self.TitlesPerc.setItemText(8, _translate("MainWindow", "40%"))
        self.TitlesPerc.setItemText(9, _translate("MainWindow", "45%"))
        self.TitlesPerc.setItemText(10, _translate("MainWindow", "50%"))
        self.TitlesPerc.setItemText(11, _translate("MainWindow", "55%"))
        self.TitlesPerc.setItemText(12, _translate("MainWindow", "60%"))
        self.TitlesPerc.setItemText(13, _translate("MainWindow", "65%"))
        self.TitlesPerc.setItemText(14, _translate("MainWindow", "70%"))
        self.TitlesPerc.setItemText(15, _translate("MainWindow", "75%"))
        self.TitlesPerc.setItemText(16, _translate("MainWindow", "80%"))
        self.TitlesPerc.setItemText(17, _translate("MainWindow", "85%"))
        self.TitlesPerc.setItemText(18, _translate("MainWindow", "90%"))
        self.TitlesPerc.setItemText(19, _translate("MainWindow", "95%"))
        self.TitlesPerc.setItemText(20, _translate("MainWindow", "100%"))
        self.Transposition.setText(_translate("MainWindow", "Transposition"))
        self.TranspositionPerc.setItemText(0, _translate("MainWindow", "0%"))
        self.TranspositionPerc.setItemText(1, _translate("MainWindow", "5%"))
        self.TranspositionPerc.setItemText(2, _translate("MainWindow", "10%"))
        self.TranspositionPerc.setItemText(3, _translate("MainWindow", "15%"))
        self.TranspositionPerc.setItemText(4, _translate("MainWindow", "20%"))
        self.TranspositionPerc.setItemText(5, _translate("MainWindow", "25%"))
        self.TranspositionPerc.setItemText(6, _translate("MainWindow", "30%"))
        self.TranspositionPerc.setItemText(7, _translate("MainWindow", "35%"))
        self.TranspositionPerc.setItemText(8, _translate("MainWindow", "40%"))
        self.TranspositionPerc.setItemText(9, _translate("MainWindow", "45%"))
        self.TranspositionPerc.setItemText(10, _translate("MainWindow", "50%"))
        self.TranspositionPerc.setItemText(11, _translate("MainWindow", "55%"))
        self.TranspositionPerc.setItemText(12, _translate("MainWindow", "60%"))
        self.TranspositionPerc.setItemText(13, _translate("MainWindow", "65%"))
        self.TranspositionPerc.setItemText(14, _translate("MainWindow", "70%"))
        self.TranspositionPerc.setItemText(15, _translate("MainWindow", "75%"))
        self.TranspositionPerc.setItemText(16, _translate("MainWindow", "80%"))
        self.TranspositionPerc.setItemText(17, _translate("MainWindow", "85%"))
        self.TranspositionPerc.setItemText(18, _translate("MainWindow", "90%"))
        self.TranspositionPerc.setItemText(19, _translate("MainWindow", "95%"))
        self.TranspositionPerc.setItemText(20, _translate("MainWindow", "100%"))
        self.MissingNameComp.setText(_translate("MainWindow", "Missing Name Component"))
        self.MissNameCompPerc.setItemText(0, _translate("MainWindow", "0%"))
        self.MissNameCompPerc.setItemText(1, _translate("MainWindow", "5%"))
        self.MissNameCompPerc.setItemText(2, _translate("MainWindow", "10%"))
        self.MissNameCompPerc.setItemText(3, _translate("MainWindow", "15%"))
        self.MissNameCompPerc.setItemText(4, _translate("MainWindow", "20%"))
        self.MissNameCompPerc.setItemText(5, _translate("MainWindow", "25%"))
        self.MissNameCompPerc.setItemText(6, _translate("MainWindow", "30%"))
        self.MissNameCompPerc.setItemText(7, _translate("MainWindow", "35%"))
        self.MissNameCompPerc.setItemText(8, _translate("MainWindow", "40%"))
        self.MissNameCompPerc.setItemText(9, _translate("MainWindow", "45%"))
        self.MissNameCompPerc.setItemText(10, _translate("MainWindow", "50%"))
        self.MissNameCompPerc.setItemText(11, _translate("MainWindow", "55%"))
        self.MissNameCompPerc.setItemText(12, _translate("MainWindow", "60%"))
        self.MissNameCompPerc.setItemText(13, _translate("MainWindow", "65%"))
        self.MissNameCompPerc.setItemText(14, _translate("MainWindow", "70%"))
        self.MissNameCompPerc.setItemText(15, _translate("MainWindow", "75%"))
        self.MissNameCompPerc.setItemText(16, _translate("MainWindow", "80%"))
        self.MissNameCompPerc.setItemText(17, _translate("MainWindow", "85%"))
        self.MissNameCompPerc.setItemText(18, _translate("MainWindow", "90%"))
        self.MissNameCompPerc.setItemText(19, _translate("MainWindow", "95%"))
        self.MissNameCompPerc.setItemText(20, _translate("MainWindow", "100%"))
        self.AlsoKnownAs.setText(_translate("MainWindow", "Also Known As"))
        self.AlsoKnownAsPerc.setItemText(0, _translate("MainWindow", "0%"))
        self.AlsoKnownAsPerc.setItemText(1, _translate("MainWindow", "5%"))
        self.AlsoKnownAsPerc.setItemText(2, _translate("MainWindow", "10%"))
        self.AlsoKnownAsPerc.setItemText(3, _translate("MainWindow", "15%"))
        self.AlsoKnownAsPerc.setItemText(4, _translate("MainWindow", "20%"))
        self.AlsoKnownAsPerc.setItemText(5, _translate("MainWindow", "25%"))
        self.AlsoKnownAsPerc.setItemText(6, _translate("MainWindow", "30%"))
        self.AlsoKnownAsPerc.setItemText(7, _translate("MainWindow", "35%"))
        self.AlsoKnownAsPerc.setItemText(8, _translate("MainWindow", "40%"))
        self.AlsoKnownAsPerc.setItemText(9, _translate("MainWindow", "45%"))
        self.AlsoKnownAsPerc.setItemText(10, _translate("MainWindow", "50%"))
        self.AlsoKnownAsPerc.setItemText(11, _translate("MainWindow", "55%"))
        self.AlsoKnownAsPerc.setItemText(12, _translate("MainWindow", "60%"))
        self.AlsoKnownAsPerc.setItemText(13, _translate("MainWindow", "65%"))
        self.AlsoKnownAsPerc.setItemText(14, _translate("MainWindow", "70%"))
        self.AlsoKnownAsPerc.setItemText(15, _translate("MainWindow", "75%"))
        self.AlsoKnownAsPerc.setItemText(16, _translate("MainWindow", "80%"))
        self.AlsoKnownAsPerc.setItemText(17, _translate("MainWindow", "85%"))
        self.AlsoKnownAsPerc.setItemText(18, _translate("MainWindow", "90%"))
        self.AlsoKnownAsPerc.setItemText(19, _translate("MainWindow", "95%"))
        self.AlsoKnownAsPerc.setItemText(20, _translate("MainWindow", "100%"))
        self.submitButton.setText(_translate("MainWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

