# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Prototype.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(571, 508)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("mslogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.InputsGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.InputsGroup.setObjectName("InputsGroup")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.InputsGroup)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.inputLabel = QtWidgets.QLabel(self.InputsGroup)
        self.inputLabel.setObjectName("inputLabel")
        self.gridLayout_4.addWidget(self.inputLabel, 0, 0, 1, 1)
        self.inputText = QtWidgets.QLineEdit(self.InputsGroup)
        self.inputText.setObjectName("inputText")
        self.gridLayout_4.addWidget(self.inputText, 0, 1, 1, 1)
        self.inputButton = QtWidgets.QToolButton(self.InputsGroup)
        self.inputButton.setObjectName("inputButton")
        self.gridLayout_4.addWidget(self.inputButton, 0, 2, 1, 1)
        self.outputLabel = QtWidgets.QLabel(self.InputsGroup)
        self.outputLabel.setObjectName("outputLabel")
        self.gridLayout_4.addWidget(self.outputLabel, 1, 0, 1, 1)
        self.outputText = QtWidgets.QLineEdit(self.InputsGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputText.sizePolicy().hasHeightForWidth())
        self.outputText.setSizePolicy(sizePolicy)
        self.outputText.setStatusTip("")
        self.outputText.setWhatsThis("")
        self.outputText.setAccessibleName("")
        self.outputText.setAutoFillBackground(False)
        self.outputText.setInputMask("")
        self.outputText.setText("")
        self.outputText.setObjectName("outputText")
        self.gridLayout_4.addWidget(self.outputText, 1, 1, 1, 1)
        self.outputButton = QtWidgets.QToolButton(self.InputsGroup)
        self.outputButton.setObjectName("outputButton")
        self.gridLayout_4.addWidget(self.outputButton, 1, 2, 1, 1)
        self.outputFileNameLabel = QtWidgets.QLabel(self.InputsGroup)
        self.outputFileNameLabel.setObjectName("outputFileNameLabel")
        self.gridLayout_4.addWidget(self.outputFileNameLabel, 2, 0, 1, 1)
        self.outputFileNameText = QtWidgets.QLineEdit(self.InputsGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputFileNameText.sizePolicy().hasHeightForWidth())
        self.outputFileNameText.setSizePolicy(sizePolicy)
        self.outputFileNameText.setStatusTip("")
        self.outputFileNameText.setWhatsThis("")
        self.outputFileNameText.setAccessibleName("")
        self.outputFileNameText.setAutoFillBackground(False)
        self.outputFileNameText.setInputMask("")
        self.outputFileNameText.setText("")
        self.outputFileNameText.setObjectName("outputFileNameText")
        self.gridLayout_4.addWidget(self.outputFileNameText, 2, 1, 1, 1)
        self.gridLayout_8.addWidget(self.InputsGroup, 0, 0, 1, 1)
        self.DistributionGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.DistributionGroup.setObjectName("DistributionGroup")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.DistributionGroup)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.TotalEstimate = QtWidgets.QLCDNumber(self.DistributionGroup)
        self.TotalEstimate.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TotalEstimate.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.TotalEstimate.setObjectName("TotalEstimate")
        self.gridLayout_5.addWidget(self.TotalEstimate, 1, 4, 1, 1)
        self.NumbeOfCasesLabel = QtWidgets.QLabel(self.DistributionGroup)
        self.NumbeOfCasesLabel.setObjectName("NumbeOfCasesLabel")
        self.gridLayout_5.addWidget(self.NumbeOfCasesLabel, 1, 0, 1, 3)
        self.NumberOfCasesText = QtWidgets.QLineEdit(self.DistributionGroup)
        self.NumberOfCasesText.setReadOnly(False)
        self.NumberOfCasesText.setClearButtonEnabled(False)
        self.NumberOfCasesText.setObjectName("NumberOfCasesText")
        self.gridLayout_5.addWidget(self.NumberOfCasesText, 1, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 1, 5, 1, 1)
        self.ForceYes = QtWidgets.QRadioButton(self.DistributionGroup)
        self.ForceYes.setChecked(True)
        self.ForceYes.setObjectName("ForceYes")
        self.gridLayout_5.addWidget(self.ForceYes, 0, 1, 1, 1)
        self.ForceLabel = QtWidgets.QLabel(self.DistributionGroup)
        self.ForceLabel.setObjectName("ForceLabel")
        self.gridLayout_5.addWidget(self.ForceLabel, 0, 0, 1, 1)
        self.ForceNo = QtWidgets.QRadioButton(self.DistributionGroup)
        self.ForceNo.setChecked(False)
        self.ForceNo.setObjectName("ForceNo")
        self.gridLayout_5.addWidget(self.ForceNo, 0, 2, 1, 1)
        self.gridLayout_8.addWidget(self.DistributionGroup, 1, 0, 1, 1)
        self.VariationCategoriesGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.VariationCategoriesGroup.setObjectName("VariationCategoriesGroup")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.VariationCategoriesGroup)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.catlabel = QtWidgets.QLabel(self.VariationCategoriesGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.catlabel.sizePolicy().hasHeightForWidth())
        self.catlabel.setSizePolicy(sizePolicy)
        self.catlabel.setObjectName("catlabel")
        self.gridLayout.addWidget(self.catlabel, 0, 0, 1, 1)
        self.Transposition = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.Transposition.setChecked(True)
        self.Transposition.setObjectName("Transposition")
        self.gridLayout.addWidget(self.Transposition, 5, 0, 1, 1)
        self.Initials = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.Initials.setChecked(True)
        self.Initials.setObjectName("Initials")
        self.gridLayout.addWidget(self.Initials, 1, 0, 1, 1)
        self.CharacterExtension = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.CharacterExtension.setChecked(True)
        self.CharacterExtension.setObjectName("CharacterExtension")
        self.gridLayout.addWidget(self.CharacterExtension, 2, 0, 1, 1)
        self.CharacterReplacement = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.CharacterReplacement.setChecked(True)
        self.CharacterReplacement.setObjectName("CharacterReplacement")
        self.gridLayout.addWidget(self.CharacterReplacement, 3, 0, 1, 1)
        self.CharacterReduction = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.CharacterReduction.setChecked(True)
        self.CharacterReduction.setObjectName("CharacterReduction")
        self.gridLayout.addWidget(self.CharacterReduction, 4, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.TranspositionPerc = QtWidgets.QSpinBox(self.VariationCategoriesGroup)
        self.TranspositionPerc.setMaximum(100)
        self.TranspositionPerc.setObjectName("TranspositionPerc")
        self.gridLayout_6.addWidget(self.TranspositionPerc, 5, 0, 1, 1)
        self.CharRepPerc = QtWidgets.QSpinBox(self.VariationCategoriesGroup)
        self.CharRepPerc.setMaximum(100)
        self.CharRepPerc.setObjectName("CharRepPerc")
        self.gridLayout_6.addWidget(self.CharRepPerc, 3, 0, 1, 1)
        self.initialsEstimate = QtWidgets.QLCDNumber(self.VariationCategoriesGroup)
        self.initialsEstimate.setAutoFillBackground(False)
        self.initialsEstimate.setFrameShape(QtWidgets.QFrame.Box)
        self.initialsEstimate.setFrameShadow(QtWidgets.QFrame.Plain)
        self.initialsEstimate.setLineWidth(1)
        self.initialsEstimate.setSmallDecimalPoint(False)
        self.initialsEstimate.setMode(QtWidgets.QLCDNumber.Dec)
        self.initialsEstimate.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.initialsEstimate.setObjectName("initialsEstimate")
        self.gridLayout_6.addWidget(self.initialsEstimate, 1, 1, 1, 1)
        self.charrepEstimate = QtWidgets.QLCDNumber(self.VariationCategoriesGroup)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.charrepEstimate.setFont(font)
        self.charrepEstimate.setFrameShape(QtWidgets.QFrame.Box)
        self.charrepEstimate.setFrameShadow(QtWidgets.QFrame.Plain)
        self.charrepEstimate.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.charrepEstimate.setObjectName("charrepEstimate")
        self.gridLayout_6.addWidget(self.charrepEstimate, 3, 1, 1, 1)
        self.CharRedPerc = QtWidgets.QSpinBox(self.VariationCategoriesGroup)
        self.CharRedPerc.setMaximum(100)
        self.CharRedPerc.setObjectName("CharRedPerc")
        self.gridLayout_6.addWidget(self.CharRedPerc, 4, 0, 1, 1)
        self.perclabel = QtWidgets.QLabel(self.VariationCategoriesGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.perclabel.sizePolicy().hasHeightForWidth())
        self.perclabel.setSizePolicy(sizePolicy)
        self.perclabel.setObjectName("perclabel")
        self.gridLayout_6.addWidget(self.perclabel, 0, 0, 1, 1)
        self.transEstimate = QtWidgets.QLCDNumber(self.VariationCategoriesGroup)
        self.transEstimate.setFrameShadow(QtWidgets.QFrame.Plain)
        self.transEstimate.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.transEstimate.setObjectName("transEstimate")
        self.gridLayout_6.addWidget(self.transEstimate, 5, 1, 1, 1)
        self.estlabel = QtWidgets.QLabel(self.VariationCategoriesGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.estlabel.sizePolicy().hasHeightForWidth())
        self.estlabel.setSizePolicy(sizePolicy)
        self.estlabel.setObjectName("estlabel")
        self.gridLayout_6.addWidget(self.estlabel, 0, 1, 1, 1)
        self.charextEstimate = QtWidgets.QLCDNumber(self.VariationCategoriesGroup)
        self.charextEstimate.setFrameShadow(QtWidgets.QFrame.Plain)
        self.charextEstimate.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.charextEstimate.setObjectName("charextEstimate")
        self.gridLayout_6.addWidget(self.charextEstimate, 2, 1, 1, 1)
        self.InitialsPerc = QtWidgets.QSpinBox(self.VariationCategoriesGroup)
        self.InitialsPerc.setMaximum(100)
        self.InitialsPerc.setObjectName("InitialsPerc")
        self.gridLayout_6.addWidget(self.InitialsPerc, 1, 0, 1, 1)
        self.CharExtPerc = QtWidgets.QSpinBox(self.VariationCategoriesGroup)
        self.CharExtPerc.setMaximum(100)
        self.CharExtPerc.setObjectName("CharExtPerc")
        self.gridLayout_6.addWidget(self.CharExtPerc, 2, 0, 1, 1)
        self.charredEstimate = QtWidgets.QLCDNumber(self.VariationCategoriesGroup)
        self.charredEstimate.setFrameShadow(QtWidgets.QFrame.Plain)
        self.charredEstimate.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.charredEstimate.setObjectName("charredEstimate")
        self.gridLayout_6.addWidget(self.charredEstimate, 4, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.catlabel_2 = QtWidgets.QLabel(self.VariationCategoriesGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.catlabel_2.sizePolicy().hasHeightForWidth())
        self.catlabel_2.setSizePolicy(sizePolicy)
        self.catlabel_2.setObjectName("catlabel_2")
        self.gridLayout_3.addWidget(self.catlabel_2, 0, 0, 1, 1)
        self.DoubleCharacters = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.DoubleCharacters.setChecked(True)
        self.DoubleCharacters.setObjectName("DoubleCharacters")
        self.gridLayout_3.addWidget(self.DoubleCharacters, 1, 0, 1, 1)
        self.Spaces = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.Spaces.setChecked(True)
        self.Spaces.setObjectName("Spaces")
        self.gridLayout_3.addWidget(self.Spaces, 2, 0, 1, 1)
        self.NameOrder = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.NameOrder.setChecked(True)
        self.NameOrder.setObjectName("NameOrder")
        self.gridLayout_3.addWidget(self.NameOrder, 3, 0, 1, 1)
        self.Titles = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.Titles.setChecked(True)
        self.Titles.setObjectName("Titles")
        self.gridLayout_3.addWidget(self.Titles, 4, 0, 1, 1)
        self.MissingNameComp = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.MissingNameComp.setChecked(True)
        self.MissingNameComp.setObjectName("MissingNameComp")
        self.gridLayout_3.addWidget(self.MissingNameComp, 5, 0, 1, 1)
        self.AlsoKnownAs = QtWidgets.QCheckBox(self.VariationCategoriesGroup)
        self.AlsoKnownAs.setEnabled(True)
        self.AlsoKnownAs.setChecked(True)
        self.AlsoKnownAs.setObjectName("AlsoKnownAs")
        self.gridLayout_3.addWidget(self.AlsoKnownAs, 6, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_3, 0, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.doublecharEstimate = QtWidgets.QLCDNumber(self.VariationCategoriesGroup)
        self.doublecharEstimate.setFrameShadow(QtWidgets.QFrame.Plain)
        self.doublecharEstimate.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.doublecharEstimate.setObjectName("doublecharEstimate")
        self.gridLayout_2.addWidget(self.doublecharEstimate, 1, 1, 1, 1)
        self.akaEstimate = QtWidgets.QLCDNumber(self.VariationCategoriesGroup)
        self.akaEstimate.setFrameShadow(QtWidgets.QFrame.Plain)
        self.akaEstimate.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.akaEstimate.setObjectName("akaEstimate")
        self.gridLayout_2.addWidget(self.akaEstimate, 6, 1, 1, 1)
        self.titlesEstimate = QtWidgets.QLCDNumber(self.VariationCategoriesGroup)
        self.titlesEstimate.setFrameShadow(QtWidgets.QFrame.Plain)
        self.titlesEstimate.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.titlesEstimate.setObjectName("titlesEstimate")
        self.gridLayout_2.addWidget(self.titlesEstimate, 4, 1, 1, 1)
        self.spacesEstimate = QtWidgets.QLCDNumber(self.VariationCategoriesGroup)
        self.spacesEstimate.setFrameShadow(QtWidgets.QFrame.Plain)
        self.spacesEstimate.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.spacesEstimate.setObjectName("spacesEstimate")
        self.gridLayout_2.addWidget(self.spacesEstimate, 2, 1, 1, 1)
        self.nameorderEstimate = QtWidgets.QLCDNumber(self.VariationCategoriesGroup)
        self.nameorderEstimate.setFrameShadow(QtWidgets.QFrame.Plain)
        self.nameorderEstimate.setMode(QtWidgets.QLCDNumber.Dec)
        self.nameorderEstimate.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.nameorderEstimate.setObjectName("nameorderEstimate")
        self.gridLayout_2.addWidget(self.nameorderEstimate, 3, 1, 1, 1)
        self.missnamecompEstimate = QtWidgets.QLCDNumber(self.VariationCategoriesGroup)
        self.missnamecompEstimate.setFrameShadow(QtWidgets.QFrame.Plain)
        self.missnamecompEstimate.setDigitCount(5)
        self.missnamecompEstimate.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.missnamecompEstimate.setObjectName("missnamecompEstimate")
        self.gridLayout_2.addWidget(self.missnamecompEstimate, 5, 1, 1, 1)
        self.NameOrderPerc = QtWidgets.QSpinBox(self.VariationCategoriesGroup)
        self.NameOrderPerc.setMaximum(100)
        self.NameOrderPerc.setObjectName("NameOrderPerc")
        self.gridLayout_2.addWidget(self.NameOrderPerc, 3, 0, 1, 1)
        self.SpacesPerc = QtWidgets.QSpinBox(self.VariationCategoriesGroup)
        self.SpacesPerc.setMaximum(100)
        self.SpacesPerc.setObjectName("SpacesPerc")
        self.gridLayout_2.addWidget(self.SpacesPerc, 2, 0, 1, 1)
        self.DoubleCharPerc = QtWidgets.QSpinBox(self.VariationCategoriesGroup)
        self.DoubleCharPerc.setMaximum(100)
        self.DoubleCharPerc.setObjectName("DoubleCharPerc")
        self.gridLayout_2.addWidget(self.DoubleCharPerc, 1, 0, 1, 1)
        self.TitlesPerc = QtWidgets.QSpinBox(self.VariationCategoriesGroup)
        self.TitlesPerc.setMaximum(100)
        self.TitlesPerc.setObjectName("TitlesPerc")
        self.gridLayout_2.addWidget(self.TitlesPerc, 4, 0, 1, 1)
        self.MissNameCompPerc = QtWidgets.QSpinBox(self.VariationCategoriesGroup)
        self.MissNameCompPerc.setMaximum(100)
        self.MissNameCompPerc.setObjectName("MissNameCompPerc")
        self.gridLayout_2.addWidget(self.MissNameCompPerc, 5, 0, 1, 1)
        self.AlsoKnownAsPerc = QtWidgets.QSpinBox(self.VariationCategoriesGroup)
        self.AlsoKnownAsPerc.setMaximum(100)
        self.AlsoKnownAsPerc.setObjectName("AlsoKnownAsPerc")
        self.gridLayout_2.addWidget(self.AlsoKnownAsPerc, 6, 0, 1, 1)
        self.perclabel_2 = QtWidgets.QLabel(self.VariationCategoriesGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.perclabel_2.sizePolicy().hasHeightForWidth())
        self.perclabel_2.setSizePolicy(sizePolicy)
        self.perclabel_2.setObjectName("perclabel_2")
        self.gridLayout_2.addWidget(self.perclabel_2, 0, 0, 1, 1)
        self.estlabel_2 = QtWidgets.QLabel(self.VariationCategoriesGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.estlabel_2.sizePolicy().hasHeightForWidth())
        self.estlabel_2.setSizePolicy(sizePolicy)
        self.estlabel_2.setObjectName("estlabel_2")
        self.gridLayout_2.addWidget(self.estlabel_2, 0, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_2, 0, 3, 1, 1)
        self.gridLayout_8.addWidget(self.VariationCategoriesGroup, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.estimateButton = QtWidgets.QPushButton(self.centralwidget)
        self.estimateButton.setObjectName("estimateButton")
        self.horizontalLayout_2.addWidget(self.estimateButton)
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setObjectName("submitButton")
        self.horizontalLayout_2.addWidget(self.submitButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 571, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.ForceNo.toggled['bool'].connect(self.NumberOfCasesText.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.InitialsPerc.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.CharExtPerc.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.CharRepPerc.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.CharRedPerc.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.TranspositionPerc.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.DoubleCharPerc.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.SpacesPerc.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.NameOrderPerc.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.TitlesPerc.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.MissNameCompPerc.setDisabled)
        self.ForceNo.toggled['bool'].connect(self.AlsoKnownAsPerc.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.inputText, self.ForceYes)
        MainWindow.setTabOrder(self.ForceYes, self.ForceNo)
        MainWindow.setTabOrder(self.ForceNo, self.NumberOfCasesText)
        MainWindow.setTabOrder(self.NumberOfCasesText, self.DoubleCharacters)
        MainWindow.setTabOrder(self.DoubleCharacters, self.CharacterExtension)
        MainWindow.setTabOrder(self.CharacterExtension, self.Spaces)
        MainWindow.setTabOrder(self.Spaces, self.CharacterReplacement)
        MainWindow.setTabOrder(self.CharacterReplacement, self.NameOrder)
        MainWindow.setTabOrder(self.NameOrder, self.CharacterReduction)
        MainWindow.setTabOrder(self.CharacterReduction, self.Titles)
        MainWindow.setTabOrder(self.Titles, self.Transposition)
        MainWindow.setTabOrder(self.Transposition, self.MissingNameComp)
        MainWindow.setTabOrder(self.MissingNameComp, self.AlsoKnownAs)
        MainWindow.setTabOrder(self.AlsoKnownAs, self.estimateButton)
        MainWindow.setTabOrder(self.estimateButton, self.submitButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Prototype"))
        self.InputsGroup.setTitle(_translate("MainWindow", "Inputs"))
        self.inputLabel.setText(_translate("MainWindow", "Input path:"))
        self.inputText.setPlaceholderText(_translate("MainWindow", "C:\\Program Files\\Your Folder\\Your Subfolder\\Your_csv.csv"))
        self.inputButton.setText(_translate("MainWindow", "..."))
        self.outputLabel.setText(_translate("MainWindow", "Output path:"))
        self.outputText.setPlaceholderText(_translate("MainWindow", "C:\\Program Files\\Your Folder\\Your Subfolder"))
        self.outputButton.setText(_translate("MainWindow", "..."))
        self.outputFileNameLabel.setText(_translate("MainWindow", "Output File Name:"))
        self.outputFileNameText.setPlaceholderText(_translate("MainWindow", "Output"))
        self.DistributionGroup.setTitle(_translate("MainWindow", "Distribution"))
        self.NumbeOfCasesLabel.setText(_translate("MainWindow", "Number of test cases to be generated:"))
        self.NumberOfCasesText.setPlaceholderText(_translate("MainWindow", "e.g. 100"))
        self.ForceYes.setText(_translate("MainWindow", "Yes"))
        self.ForceLabel.setText(_translate("MainWindow", "Force Distribution:"))
        self.ForceNo.setText(_translate("MainWindow", "No"))
        self.VariationCategoriesGroup.setTitle(_translate("MainWindow", "Variation Categories"))
        self.catlabel.setText(_translate("MainWindow", "Categories"))
        self.Transposition.setText(_translate("MainWindow", "Transposition"))
        self.Initials.setText(_translate("MainWindow", "Initials"))
        self.CharacterExtension.setText(_translate("MainWindow", "Character Extension"))
        self.CharacterReplacement.setText(_translate("MainWindow", "Character Replacement"))
        self.CharacterReduction.setText(_translate("MainWindow", "Character Reduction"))
        self.perclabel.setText(_translate("MainWindow", "%"))
        self.estlabel.setText(_translate("MainWindow", "Estimate"))
        self.catlabel_2.setText(_translate("MainWindow", "Categories"))
        self.DoubleCharacters.setText(_translate("MainWindow", "Double Characters"))
        self.Spaces.setText(_translate("MainWindow", "Spaces"))
        self.NameOrder.setText(_translate("MainWindow", "Name Order"))
        self.Titles.setText(_translate("MainWindow", "Titles"))
        self.MissingNameComp.setText(_translate("MainWindow", "Missing Name Component"))
        self.AlsoKnownAs.setText(_translate("MainWindow", "Also Known As"))
        self.perclabel_2.setText(_translate("MainWindow", "%"))
        self.estlabel_2.setText(_translate("MainWindow", "Estimate"))
        self.estimateButton.setText(_translate("MainWindow", "Estimate"))
        self.submitButton.setText(_translate("MainWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

